server:
  port: 8888
spring:
  thymeleaf:
   prefix: classpath:/templates/
   suffix: .html
   mode: HTML5
   encoding: UTF-8
  datasource:
   url: jdbc:mysql://localhost:3306/jdbc?useUnicode=true&characterEncoding=UTF-8
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity