/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.46
 * Generated at: 2021-04-04 02:04:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/JavaCode/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1560654862000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <title>图书馆管理系统</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" type=\"text/css\"></link>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mycss.css\" type=\"text/css\"></link>\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrapValidator.min.js\"></script>\n");
      out.write("   <script>\n");
      out.write("        $(function(){\n");
      out.write("            //客户端表单校验，使用bootstrapValidator插件\n");
      out.write("            $('#frmLogin').bootstrapValidator({\n");
      out.write("                feedbackIcons:{\n");
      out.write("                    valid:'glyphicon glyphicon-ok',\n");
      out.write("                    invalid:'glyphicon glyphicon-remove',\n");
      out.write("                    validating:'glyphicon glyphicon-refresh'\n");
      out.write("                },\n");
      out.write("                fields:{\n");
      out.write("                    code:{\n");
      out.write("                        validators:{\n");
      out.write("                            notEmpty:{\n");
      out.write("                                message:'用户名不能为空'\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    },\n");
      out.write("                    password: {\n");
      out.write("                        validators: {\n");
      out.write("                            notEmpty: {\n");
      out.write("                                message: '密码不能为空'\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>    \n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  \t<!-- 使用自定义css样式 div-signin 完成元素居中-->\n");
      out.write("    <div class=\"container div-signin\">\n");
      out.write("      <div class=\"panel panel-primary div-shadow\">\n");
      out.write("      \t<!-- h3标签加载自定义样式，完成文字居中和上下间距调整 -->\n");
      out.write("\t    <div class=\"panel-heading\">\n");
      out.write("\t    \t<h3>图书馆管理系统</h3>\n");
      out.write("\t    \t<span>Library Management System</span>\n");
      out.write("\t    </div>\n");
      out.write("\t    <div class=\"panel-body\">\n");
      out.write("\t      <!-- login form start -->\n");
      out.write("\t      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"form-horizontal\" method=\"post\" id=\"frmLogin\">\n");
      out.write("\t\t     <div class=\"form-group\">\n");
      out.write("\t\t       <label class=\"col-sm-3 control-label\">用户名：</label>\n");
      out.write("\t\t       <div class=\"col-sm-9\">\n");
      out.write("\t\t         <input class=\"form-control\" type=\"text\" placeholder=\"请输入用户名\" name=\"code\">\n");
      out.write("\t\t       </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t     <div class=\"form-group\">\n");
      out.write("\t\t       <label class=\"col-sm-3 control-label\">密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>\n");
      out.write("\t\t       <div class=\"col-sm-9\">\n");
      out.write("\t\t         <input class=\"form-control\" type=\"password\" placeholder=\"请输入密码\" name=\"password\">\n");
      out.write("\t\t       </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t     <div class=\"form-group\">\n");
      out.write("\t\t       <label class=\"col-sm-3 control-label\">身&nbsp;&nbsp;&nbsp;&nbsp;份：</label>\n");
      out.write("\t\t       <div class=\"col-sm-9\">\n");
      out.write("\t\t       \t <select class=\"form-control\" name=\"loginType\">\n");
      out.write("\t\t       \t \t<option value=\"0\">-请选择身份-</option>\n");
      out.write("\t\t       \t \t<option value=\"1\">普通用户</option>\n");
      out.write("\t\t       \t \t<option value=\"2\">管理员</option>\n");
      out.write("\t\t       \t \t<option value=\"3\">系统管理员</option>\n");
      out.write("\t\t       \t </select>\n");
      out.write("\t\t       </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t    <div class=\"form-group\">\n");
      out.write("\t\t       <div class=\"col-sm-3\">\n");
      out.write("\t\t       </div>\n");
      out.write("\t\t       <div class=\"col-sm-9 padding-left-0\">\n");
      out.write("\t\t       \t <div class=\"col-sm-4\">\n");
      out.write("\t\t\t         <button type=\"submit\" class=\"btn btn-primary btn-block\">登&nbsp;&nbsp;陆</button>\n");
      out.write("\t\t       \t </div>\n");
      out.write("\t\t       \t <div class=\"col-sm-4\">\n");
      out.write("\t\t\t         <button type=\"reset\" class=\"btn btn-primary btn-block\">重&nbsp;&nbsp;置</button>\n");
      out.write("\t\t       \t </div>\n");
      out.write("\t\t       \t <div class=\"col-sm-4\" style=\"padding:0;margin-left:-10px;width:auto;padding-top: 5px;\">\n");
      out.write("\t\t       \t \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t       \t </div>\n");
      out.write("\t\t       </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t      </form>\n");
      out.write("\t      <!-- login form end -->\n");
      out.write("\t    </div>\n");
      out.write("\t  </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 页尾 版权声明 -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("\t\t<div class=\"col-sm-12 foot-css\">\n");
      out.write("\t\t        <p class=\"text-muted credit\">\n");
      out.write("\t\t            <!-- Copyright &nbsp;&nbsp; 版权所有 -->\n");
      out.write("\t\t        </p>\n");
      out.write("\t    </div>\n");
      out.write("    </div>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/login.jsp(90,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t       \t\t<span class=\"text-danger\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("\t\t\t       ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
